name: deploy-ci cd project

on:
  push:
    branches: [main]

jobs:
  test:
    name: test quality of code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, mysql, zip
          coverage: none

      - name: install php dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: copy .env
        run: cp .env.example .env

      - name: generate application key
        run: php artisan key:generate

      - name: execute unit test
        run: php artisan test

  deploy:
    name: deploy on digtal ocean
    runs-on: ubuntu-latest
    needs: test

    steps:
       - name: checkout code
         uses: actions/checkout@v4

       - name: Setup ssh key
         run: |
            echo "${{  secrets.SSH_KEY  }}" > id_rsa
            chmod 600 id_rsa

       - name: Deploy via ssh
         run: |
            ssh -i id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
              cd ${{ secrets.SSH_DIR }}
              git pull origin main
              composer install
              php artisan migrate
              php artisan optimize
              php artisan config:clear
              php artisan route:cache
            EOF



